### PR TITLE
chore: Release v0.11.0

### PR DESCRIPTION
**Pull request by jetuk**
I messed up the commit message on the last commit :(

### CODE REVIEW

**Comment by Batch21** [comment]
> I messed up the commit message on the last commit :(

are you going to add it to the changelog manually?

**Comment by jetuk** [comment]
Shall I force push to main?!

**Comment by Batch21** [comment]
> Shall I force push to main?!

yeah, why not. I won't tell anyone!

Is there any CI that could check commit formats? I guess it wouldn't really work if you're creating merge commits using the GitHub UI....

**Comment by jetuk** [comment]
@Batch21 are you happy with this?

**Review by Batch21 — APPROVED** [review]

**Pull request merged**
